// ACTIONS
export const SET_VIEW_STATE = 'SET_VIEW_STATE';
export const CARD_INSERTED = 'CARD_INSERTED';
export const PIN_ENTERED = 'PIN_ENTERED';
export const SCREEN_ACTION = 'SCREEN_ACTION';
export const MONEY_ACTION = 'MONEY_ACTION';
export const CANCEL_ACTION = 'CANCEL_ACTION';
